import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import ButtonCount from "../components/buttons";
import ButtonReset from "../components/resetButton";
import {
  Container,
  MainSection,
  Title,
  DescriptionSection,
  Grid,
  Card,
  Footer,
} from "../styles/styles";
import { Stack } from "@chakra-ui/react";
import { intialState, selectorSize } from "../utils/store";
import { useRecoilState, useRecoilValue } from "recoil";

const Home: NextPage = () => {
  const [count, ___] = useRecoilState(intialState);

  const containerSize = useRecoilValue(selectorSize);

  return (
    <Container>
      <Head>
        <title>Recoil React Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainSection>
        <Title>
          React Recoil <a href="https://nextjs.org">State Management !</a>
        </Title>

        <DescriptionSection>Get started by editing </DescriptionSection>

        <Grid>
          <Card>
            <h2>Count : {count}</h2>
            <p></p>
          </Card>

          <Card>
            <h2>You Can Learn more from me &rarr;</h2>
            <p>at DanWare Academy</p>
          </Card>

          <Card style={{ fontSize: containerSize }}>
            <h2>Changed Size &rarr;</h2>
            <p>Based on State</p>
          </Card>

          <Card>
            <h2>I trust &rarr;</h2>
            <p>you will enjoy an easy way of state management</p>
          </Card>
          <Stack direction="row" spacing={4} align="center">
            <ButtonCount />
            <ButtonReset />
          </Stack>
        </Grid>
      </MainSection>

      <Footer>
        <a
          href="https://github.com/dantelentsoe"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by <Link href="http://dantelentsoe.com">Dante Lentsoe</Link>
        </a>
      </Footer>
    </Container>
  );
};

export default Home;
